import { Link } from 'react-router-dom'
import { buttonStyle, secondaryStyle } from '../../components/FormField'
import { portals, PortalIcon } from '../../components/PortalIdentity'
import { authPath } from '../../context/roleHome'
import MatchingExample from './MatchingExample'

const steps = ['Profile', 'Match', 'Schedule', 'Offer', 'Review']
const features = [
  ['01', 'Build a complete picture', 'Bring profile evidence, resume text, and preparation into one place. See the factors behind your readiness.'],
  ['02', 'Make an informed shortlist', 'Compare candidates against role requirements. Review skills, eligibility, and the reason behind every match.'],
  ['03', 'Keep every next step connected', 'Check interview conflicts, track each offer stage, and review recorded placement outcomes.'],
]
export default function LandingPage() {
  return <>
    <section className="border-b border-line bg-white px-5 py-16 sm:px-8 lg:py-24">
      <div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1fr_1fr]">
        <div><p className="flex items-center gap-2 text-xs font-semibold tracking-wide text-muted"><span className="h-2 w-2 rounded-full bg-growth" aria-hidden="true" />EXPLAINABILITY-FIRST CAMPUS PLACEMENT</p>
          <h1 className="mt-6 max-w-xl text-5xl font-semibold leading-[1.08] tracking-[-0.045em] text-navy sm:text-6xl">Move placements<br />forward.<br /><span className="text-saffron-deep">With clarity.</span></h1>
          <p className="mt-6 max-w-lg text-lg leading-8 text-muted">One connected workspace for students, recruiters, and placement teams. From the first profile to the next career milestone.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Link to="/auth" className={buttonStyle}>Open your workspace <span className="ml-3" aria-hidden="true">→</span></Link><a href="#explainability" className={secondaryStyle + ' inline-flex items-center'}>Explore the workflow</a></div>
          <p className="mt-6 text-sm text-muted">Clear factors. Practical next steps. Human decisions.</p>
        </div>
        <div className="overflow-hidden rounded-2xl border border-line bg-paper shadow-xl shadow-navy/5">
          <div className="flex items-center justify-between border-b border-line bg-white px-6 py-4"><p className="text-sm font-semibold text-navy">Your placement workspace</p><span className="rounded-full bg-warning-soft px-3 py-1 text-xs font-medium text-saffron-deep">Workflow preview</span></div>
          <div className="p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-muted">From preparation to placement</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-navy">Every step has a clear next action.</h2>
            <div className="mt-7 space-y-3">{[['Profile & readiness','Review evidence and understand your preparation.','student'],['Roles & shortlists','Compare requirements and inspect every factor.','recruiter'],['Interviews & offers','Coordinate schedules and follow recorded stages.','admin']].map(([title,copy,role]) => <div key={title} className="flex items-start gap-4 rounded-xl border border-line bg-white p-4"><span className="rounded-lg bg-paper p-2.5 text-navy"><PortalIcon role={role} className="h-5 w-5" /></span><div><h3 className="text-sm font-semibold text-navy">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{copy}</p></div></div>)}</div>
            <p className="mt-5 text-xs leading-5 text-muted">Illustrative workflow · no live results shown in this preview.</p>
          </div>
        </div>
      </div>
    </section>
    <div className="border-b border-line bg-paper px-5 py-6 sm:px-8"><ol className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4">{steps.map((step,i) => <li key={step} className="flex items-center gap-3 text-sm font-medium text-navy"><span className="font-mono text-xs text-muted">0{i+1}</span>{step}{i<steps.length-1 && <span aria-hidden="true" className="ml-4 text-line">→</span>}</li>)}</ol></div>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-20"><p className="text-xs font-semibold uppercase tracking-widest text-saffron-deep">One connected process</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">Less coordination. More progress.</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{features.map(([n,title,copy]) => <article key={n} className="border-t border-line pt-6"><p className="text-sm font-semibold text-saffron-deep">{n}</p><h3 className="mt-4 text-xl font-semibold text-navy">{title}</h3><p className="mt-3 text-sm leading-7 text-muted">{copy}</p></article>)}</div></section>
    <section id="portals" className="scroll-mt-24 border-y border-line bg-white px-5 py-16 sm:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-widest text-saffron-deep">Built around your role</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-navy">Your work. Your workspace.</h2><div className="mt-8 grid gap-5 lg:grid-cols-3">{portals.map(p => <article key={p.role} className="flex flex-col rounded-xl border border-line bg-white p-6 transition hover:border-navy/30 hover:shadow-lg hover:shadow-navy/5"><span className="inline-flex w-fit rounded-lg bg-paper p-3 text-navy"><PortalIcon role={p.role} /></span><p className="mt-5 text-xs font-medium uppercase tracking-widest text-muted">{p.label}</p><h3 className="mt-2 text-xl font-semibold text-navy">{p.name}</h3><p className="mt-3 text-sm leading-7 text-muted">{p.description}</p><ul className="mb-6 mt-5 space-y-2 text-sm text-navy">{p.features.map(f => <li key={f}><span className="mr-2 text-growth" aria-hidden="true">✓</span>{f}</li>)}</ul><Link to={authPath(p.role)} className="mt-auto flex justify-between border-t border-line pt-4 text-sm font-semibold text-navy hover:underline">Continue as {p.label}<span aria-hidden="true">→</span></Link></article>)}</div></div></section>
    <section id="explainability" className="mx-auto grid max-w-7xl scroll-mt-24 gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[0.85fr_1.15fr] lg:py-20"><div><p className="text-xs font-semibold uppercase tracking-widest text-saffron-deep">Decisions you can inspect</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-tight text-navy sm:text-4xl">See the score.<br />Understand the reason.</h2><p className="mt-5 leading-7 text-muted">A useful match explains what fits, what needs work, and where to go next. Every score comes with its contributing factors and a plain-language explanation.</p><ol className="mt-7 space-y-4 text-sm text-navy">{['Review the full factor breakdown.','Identify specific skill and eligibility gaps.','Keep the final decision with a person.'].map((t,i) => <li key={t} className="flex gap-3"><span className="text-saffron-deep">0{i+1}</span>{t}</li>)}</ol><p className="mt-7 text-xs leading-6 text-muted">Matching uses keyword comparison and weighted rules. Starting weights are unvalidated assumptions. Optional trained placement models are shown separately.</p></div><MatchingExample /></section>
    <section className="bg-navy-dark px-5 py-14 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-xs font-semibold uppercase tracking-widest text-saffron">Your Next Jugaad</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">Make the next step a clear one.</h2><p className="mt-3 text-sm text-white/70">Choose your role and pick up where you left off.</p></div><Link to="/auth" className={buttonStyle}>Open JobJugaad →</Link></div></section>
  </>
}
