import { Link } from 'react-router-dom'
export default function PrivacyPage() {
  return <article className="mx-auto max-w-3xl space-y-5 rounded-2xl border border-line bg-white p-6 sm:p-8">
    <h1 className="text-3xl font-bold text-navy">Privacy & retention</h1><p className="text-sm text-muted">Effective October 4, 2026 · Operational notice, not a claim of legal certification.</p>
    <h2 className="text-xl font-bold text-navy">What your workspace records</h2><p>Registered email, college and role; profile, resume text, academic and skill inputs; applications, interview/offer history, private PDFs, assessment declarations, announcements and human reviews. Email verification and password recovery use your configured mail provider. Hiring messages remain in-app.</p>
    <h2 className="text-xl font-bold text-navy">Who can access it</h2><p>You see your own records. Approved recruiters see candidates in their college for owned drives. Authorized college staff review placement and support records. Application college filters, role/ownership checks and PostgreSQL Row-Level Security provide separate enforcement layers. Directory selection alone does not verify enrollment.</p>
    <h2 className="text-xl font-bold text-navy">Why records are retained</h2><p>Active placement records support scheduling, recruitment and offer administration. On a deletion request, the college must review within 30 days and document any continuing placement/audit retention need. Restricting sign-in does not erase those records. No universal employer/legal retention period is asserted; the college must define and communicate its record-specific policy before final erasure. Expired verification/reset tokens and hashed authentication-limit records are eligible for maintenance cleanup after seven days.</p>
    <h2 className="text-xl font-bold text-navy">Your controls</h2><p>Use Account & data to export directly owned JSON records, request deletion, withdraw a pending request, and revoke current sessions. Offer PDF files use authenticated downloads. Contact your college placement administrator for access correction, retention review or final erasure. Do not include passwords or reset links in support requests.</p>
    <h2 className="text-xl font-bold text-navy">Data and scoring limits</h2><p>Archived demonstration records are synthetic. Public-data placement classifiers have their own provenance and limitations. Readiness/matching/support use explained rules; profile scores are self-reported unless separately shown as staff-recorded evidence. No privacy, fairness or prediction guarantee is made.</p>
    <h2 className="text-xl font-bold text-navy">Backups and service providers</h2><p>Hosting uses Vercel and Render PostgreSQL; account email uses the configured Gmail API or Resend provider. Encrypted backups require owner-controlled keys and private storage. Erasure requests must also be considered when restoring backups; restored restricted accounts must not be reactivated silently. Production backup coverage and off-site continuity require owner verification.</p>
    <Link className="inline-block text-navy underline" to="/account">Account & data →</Link>
  </article>
}
